### ISSUE TITLE
Quintet Compression does not find max length matches.

### ISSUE THREAD

**Issue by Tranquilite0** [Osteoclave/game-tools#1]
The Quintet compression algorithm will only match up to a maximum of 15 bytes when the maximum supported by the decompression algorithm is 17.

Problematic line of code is here:
https://github.com/Osteoclave/game-tools/blob/8edc2560da38ed51648eb6fbeffafe212a85e308/snes/quintet_comp.py#L47

Change it to `LOOKAHEAD_SIZE + 1,` and the problem is solved. I was having trouble with decompressed and then recompressed data no longer fitting in the same space in ROM while doing Soul Blazer romhacking prior to making this change.

**Comment by Osteoclave** [comment]
Oops! Well-spotted. Should be fixed now.
